package main

import (
	"strings"
	"testing"
	"time"
)

func TestCodeToSubmit(t *testing.T) {
	solvedAt := time.Date(2025, 1, 15, 10, 0, 0, 0, time.UTC)
	sol := Solution{
		Lang:      "python3",
		Model:     "gpt-4o",
		TypedCode: "class Solution:\n    def twoSum(self):\n        pass\n",
		SolvedAt:  solvedAt,
	}

	t.Run("with metadata comment", func(t *testing.T) {
		code, err := codeToSubmit(sol, true)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.HasPrefix(code, "# leetgptsolver submission\n") {
			t.Errorf("expected comment header, got: %s", code)
		}
		if !strings.Contains(code, "solution generated by model gpt-4o") {
			t.Errorf("expected model info in comment, got: %s", code)
		}
		if !strings.Contains(code, sol.TypedCode) {
			t.Errorf("expected typed code in output, got: %s", code)
		}
	})

	t.Run("without metadata comment", func(t *testing.T) {
		code, err := codeToSubmit(sol, false)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if code != sol.TypedCode {
			t.Errorf("expected %q, got %q", sol.TypedCode, code)
		}
	})

	t.Run("rust struct cleanup", func(t *testing.T) {
		rustSol := Solution{
			Lang:      "rust",
			Model:     "gpt-4o",
			TypedCode: "pub struct Solution;\nimpl Solution {\n    pub fn test() {}\n}\n",
			SolvedAt:  solvedAt,
		}
		code, err := codeToSubmit(rustSol, false)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if strings.Contains(code, "pub struct Solution;\n") {
			t.Errorf("expected 'pub struct Solution;' to be removed, got: %s", code)
		}
	})

	t.Run("unsupported language error", func(t *testing.T) {
		unsupportedSol := Solution{
			Lang:      "brainfuck",
			Model:     "gpt-4o",
			TypedCode: "+++",
			SolvedAt:  solvedAt,
		}
		_, err := codeToSubmit(unsupportedSol, true)
		if err == nil {
			t.Fatalf("expected error for unsupported language, got nil")
		}
	})
}
