package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"time"
	"whisk/leetcode-scraper/throttler"

	"github.com/rs/zerolog/log"
	"github.com/spf13/viper"
)

var lcThrottler throttler.Throttler

func submit(files []string) {
	sentCnt := 0
	submittedCnt := 0
	lcThrottler = throttler.NewThrottler(1 * time.Second)
	for _, file := range files {
		log.Info().Msgf("Submitting problem %s ...", file)

		var problem Problem
		err := readProblem(&problem, file)
		if err != nil {
			log.Err(err).Msg("Failed to read problem")
			continue
		}
		for llm, solv := range problem.Solutions {
			if solv.TypedCode == "" {
				log.Error().Msg("No solution to submit")
				continue
			}
			subm, ok := problem.Submissions[llm]
			if !viper.GetBool("force") && (ok && subm.CheckResponse.Finished) {
				log.Info().Msg("Already submitted")
				continue
			}
			submission, err := submitAndCheckSolution(problem.Question, solv)
			sentCnt += 1
			if err != nil {
				log.Err(err).Msg("Failed to submit or check the solution")
				continue
			}
			log.Info().Msgf("Submission result: %s", submission.CheckResponse.StatusMsg)
			problem.Submissions[llm] = *submission
			err = saveProblemInto(problem, file)
			if err != nil {
				log.Err(err).Msg("Failed to save the submission")
				continue
			}
			submittedCnt += 1
		}
	}
	log.Info().Msgf("Submitted %d/%d", submittedCnt, len(files))
}

func submitAndCheckSolution(q Question, s Solution) (*Submission, error) {
	subReq := SubmitRequest{
		Lang:       s.Lang,
		QuestionId: q.Data.Question.Id,
		TypedCode:  codeToSubmit(s),
	}

	url := "https://leetcode.com/problems/" + q.Data.Question.TitleSlug + "/submit/"
	submissionId, err := submitCode(url, subReq)
	if err != nil {
		return nil, err
	}
	url = fmt.Sprintf("https://leetcode.com/submissions/detail/%d/check/", submissionId)

	checkResponse, err := checkStatus(url, submissionId, 30*time.Second)
	if err != nil {
		return nil, err
	}

	return &Submission{
		SubmitRequest: subReq,
		SubmissionId:  submissionId,
		CheckResponse: *checkResponse,
	}, nil
}

func submitCode(url string, subReq SubmitRequest) (uint64, error) {
	var reqBody bytes.Buffer
	// use encoder, not standard json.Marshal() because we don't need to escape "<", ">" etc. in the source code
	encoder := json.NewEncoder(&reqBody)
	encoder.SetEscapeHTML(false)
	err := encoder.Encode(subReq)
	if err != nil {
		return 0, fmt.Errorf("failed marshalling GraphQL: %w", err)
	}
	log.Trace().Msgf("Submission request body:\n%s", reqBody.String())
	var respBody []byte
	for lcThrottler.Wait() {
		var code int
		respBody, code, err = makeAuthorizedHttpRequest("POST", url, &reqBody)
		if code == http.StatusTooManyRequests {
			lcThrottler.Slower()
			continue
		}
		if err != nil {
			lcThrottler.Slower()
			break
		}
		log.Debug().Msgf("Submission response body:\n%s", string(respBody))
		lcThrottler.Complete()
	}
	if err != nil {
		return 0, err
	}
	if err = lcThrottler.Error(); err != nil {
		log.Err(err).Msgf("throttler error")
	}

	var respStruct map[string]uint64
	err = json.Unmarshal(respBody, &respStruct)
	if err != nil {
		return 0, fmt.Errorf("failed unmarshalling submission response: %w", err)
	}
	submissionId := respStruct["submission_id"]
	if submissionId <= 0 {
		return 0, fmt.Errorf("invalid submission id")
	}
	log.Debug().Msgf("Got submission_id %d", submissionId)

	return submissionId, nil
}

func checkStatus(url string, submissionId uint64, maxWaitTime time.Duration) (*CheckResponse, error) {
	var checkResp CheckResponse
	for lcThrottler.Wait() {
		respBody, code, err := makeAuthorizedHttpRequest("GET", url, bytes.NewReader([]byte{}))
		if code == http.StatusTooManyRequests {
			lcThrottler.Slower()
			continue
		}
		if err != nil {
			lcThrottler.Slower()
			return nil, err
		}
		log.Trace().Msgf("Check response body:\n%s", string(respBody))

		err = json.Unmarshal(respBody, &checkResp)
		if err != nil {
			return nil, fmt.Errorf("failed unmarshalling check response: %w", err)
		}
		if checkResp.Finished {
			lcThrottler.Complete()
		} else {
			lcThrottler.Again()
		}
	}
	if err := lcThrottler.Error(); err != nil {
		log.Err(err).Msgf("throttler error")
	}
	return &checkResp, nil
}

func codeToSubmit(s Solution) string {
	return "# leetgptsolver submission\n" +
		fmt.Sprintf("# solution generated by model %s at %s \n", s.Model, s.SolvedAt) +
		s.TypedCode
}
